---
int32 xsize
int32 ysize
int32 xRobot
int32 yRobot
float32 angleRobot
int32[] voronodesx
int32[] voronodesy
int32[] neighborsFirst
int32[] neighborsLast
int32[] goalsx
int32[] goalsy
int32[] coverageLimitsx
int32[] coverageLimitsy
int32[] victimsx
int32[] victimsy
int32[] victimsToGox
int32[] victimsToGoy
int32[] sensorID
int32 victimAppPointx
int32 victimAppPointy
int32[] victimAppPointsx
int32[] victimAppPointsy	

