Header header
uint8 stateLeft
uint8 stateRight
int32 currentLeft #in mA
int32 currentRight #in mA
int32 velocityLeft #in rpm
int32 velocityRight #in rpm
float32 velocityLinear #in m/s
float32 velocityAngular #in rad/s
int32 powerLeft #in mW
int32 powerRight #in mW
float32 efficiencyLeft #percentage 0-100
float32 efficiencyRight #percentage 0-100
mainMotorControl_communications/motorErrorMsg error
